# Generated by Django 3.1.7 on 2022-02-20 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game_lives',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
